mod syntax;

mod consts {
    const dec_num = 616;
    const hex_num = 0xFFFF;
    const bin_num = 0b10101;
    const octal_num = 0o666;
    const float_num = 0.5e4;

    fn main() {}
}

const f = 1.0 / 2.0;
const i = 1 / 2;

fn main() void {
    print("hello");
    const XXX = consts::main;
}

pub(pkg) fn my_fn(a: float) {}

mod my_module {
    pub fn new_func() {}
    pub fn other_func() {}

    pub mod nested_module {
        pub fn nested_func() {}
    }
}

